# Generated by Django 5.2 on 2025-05-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_certificate_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images/'),
        ),
    ]
