# Generated by Django 5.2 on 2025-05-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_course_remove_batch_created_by_and_more'),
    ]

    operations = [
    ]
