# Generated by Django 5.2 on 2025-06-01 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_image_alter_quiz_image'),
        ('users', '0010_auto_20250601_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
