# Generated by Django 5.2 on 2025-06-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_course_alter_batch_course_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE users_batch ADD COLUMN course_id INTEGER NULL;
            """,
            """
            ALTER TABLE users_batch DROP COLUMN course_id;
            """
        ),
    ]