# Generated by Django 5.2 on 2025-06-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE users_student ADD COLUMN course_id INTEGER NULL;
            """,
            """
            ALTER TABLE users_student DROP COLUMN course_id;
            """
        ),
    ]