# Generated by Django 5.2 on 2025-06-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_feestructure_feeinstallment_studentfee_feepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
