# Generated by Django 5.2 on 2025-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
