# Generated by Django 5.2 on 2025-05-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_quiz_image_alter_workshop_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
