# Generated by Django 5.2 on 2025-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_discount_price_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text='YouTube playlist ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('url', 'Direct URL'), ('youtube', 'YouTube Video')], default='url', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=50, null=True),
        ),
    ]
