# Generated by Django 5.2 on 2025-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_youtube_playlist_id_video_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_duration',
            field=models.IntegerField(default=300, help_text='Preview duration in seconds (default: 5 minutes)'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='URL for the preview video (first video of playlist)', null=True),
        ),
    ]
